// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3R45elbqUpS8jJgeL1jGbQ5To5lTq7A',
    appId: '1:443979310639:web:261b09dc5c62f9781f88da',
    messagingSenderId: '443979310639',
    projectId: 'newavenue-7bd1d',
    authDomain: 'newavenue-7bd1d.firebaseapp.com',
    storageBucket: 'newavenue-7bd1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerkwE_UWnLSenhhkxcwAcDrbAaE0xvYI',
    appId: '1:443979310639:android:75c996055bd361731f88da',
    messagingSenderId: '443979310639',
    projectId: 'newavenue-7bd1d',
    storageBucket: 'newavenue-7bd1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZbGD3bumfxe0LCc2gXhAf411PA3XbYM',
    appId: '1:443979310639:ios:473a5b009aa269a11f88da',
    messagingSenderId: '443979310639',
    projectId: 'newavenue-7bd1d',
    storageBucket: 'newavenue-7bd1d.appspot.com',
    androidClientId: '443979310639-mej1bqdom6kcqjuf86ttc8totbpk3dij.apps.googleusercontent.com',
    iosClientId: '443979310639-rtr2roeag54vf5pb2eia7uutsjm0vf8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.newavenue',
  );
}
